# buildifier: disable=no-effect
cxx_binary(
    name = "test",
    srcs = ["test_main.cpp"],
    link_style = "static",
    deps = ["//lib:library",
            "//third-party:argparse",
            "//third-party:gmp",
            "//third-party:gtest",
            "//third-party:rapidcheck"],
    visibility = ["PUBLIC"],
)
